### ISSUE TITLE
Create Example Templates

### ISSUE THREAD

**Issue by elicharlese** [elicharlese/ForSure-CLI#6]
## Example Templates

Create a set of example templates demonstrating ForSure CLI capabilities.

### Template Categories

1. Basic Templates
   - [ ] Empty project
   - [ ] Hello World
   - [ ] README template
   - [ ] License templates

2. Web Development
   - [ ] Static website
   - [ ] React application
   - [ ] Vue.js project
   - [ ] Next.js setup

3. Rust Projects
   - [ ] Basic library
   - [ ] Command-line tool
   - [ ] Web service
   - [ ] Full-stack application

4. Development Tools
   - [ ] GitHub Actions workflow
   - [ ] Docker configuration
   - [ ] Development environment
   - [ ] Testing setup

### Template Structure
```markdown name=docs/TEMPLATES.md
# ForSure Example Templates

## Template Organization

Each template follows this structure:
```
template-name/
├── .forsure
├── template/
│   ├── src/
│   ├── tests/
│   └── docs/
├── hooks/
│   ├── pre-generate/
│   └── post-generate/
└── README.md
```

## Basic Templates

### Empty Project

Minimal project structure with essential files.

```toml
# .forsure
name = "empty-project"
version = "1.0.0"
description = "Empty project template"

[variables]
author = ""
email = ""
license = "MIT"

[files]
README.md = """
# {{project-name}}

Created by {{author}}
"""

LICENSE = """
MIT License
Copyright (c) {{year}} {{author}}
...
"""
```

### Web Application

React application with TypeScript and testing setup.

```toml
# .forsure
name = "react-typescript"
version = "1.0.0"
description = "React TypeScript template"

[variables]
author = ""
email = ""
node_version = ">=16"

[dependencies]
typescript = "^4.5.0"
react = "^18.0.0"
jest = "^27.0.0"

[hooks.pre-generate]
- "npm install"
- "npm run build"

[hooks.post-generate]
- "git init"
- "npm test"
```
```

### Implementation Details
- [ ] File templates
- [ ] Variable substitution
- [ ] Hook scripts
- [ ] Validation rules
- [ ] Documentation

### Testing Guidelines
- [ ] Template validation
- [ ] Generation testing
- [ ] Hook execution
- [ ] Error scenarios
- [ ] Clean-up procedures

### Documentation
- [ ] Template usage
- [ ] Customization options
- [ ] Best practices
- [ ] Example outputs
- [ ] Troubleshooting

### Review Process
1. Template functionality testing
2. Documentation review
3. Example verification
4. User experience testing
